version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cvdb
    volumes:
      # Scripts only run if data directory is empty (from official docs)
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=cvdb
    ports:
      - "8081:8081"

  client:
    build:
      context: client
      dockerfile: Dockerfile

    ports:
      - "8080:80"

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"

    # fixes issue where containerized nginx cannot resolve 'host.docker.internal' on Linux 
    extra_hosts:
      - "host.docker.internal:host-gateway"
