version: "3.8"

services:
  db: 
    image: postgres:13.4-alpine3.14
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cvdb
    volumes:
      # Scripts only run it data directory is empty (from official docs)
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  server: 
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=0.0.0.0
      - DB_PORT=5433
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=cvdb
    ports: 
      - "8081:8081"

  client:
    build: 
      context: client
      dockerfile: Dockerfile

    ports:
      - "8080:80"