version: "3.8"

services:
  db: 
    image: postgres
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cvdb