# This workflow compiles code with Elm and uploads it to s3 static site http://contest-viewer.s3-website-us-east-1.amazonaws.com/

name: CI-contest-viewer

# Workflow will run on push to master
on:
  # Triggers the workflow on push request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of two jobs that build and deploy. Jobs run sequentially
jobs:
  # Two job called "build" and "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git clone files
        uses: actions/checkout@v3
      
      # AWS programmatic access to the bucket s3://contest-viewer with permissions
      #- name: Configure AWS access
      # uses: aws-actions/

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
